/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/coop/Projects/nim/tic_tac_toe/nimcache/stdlib_parseopt2.o /home/coop/Projects/nim/tic_tac_toe/nimcache/stdlib_parseopt2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw;
struct tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w {
  RootObj Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmd;
NI pos;
NimStringDesc* remainingShortOptions;
tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw kind;
NimStringDesc* key;
NimStringDesc* val;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef NIM_CHAR tyArray_1N75LKnZklmK4NsXtZ9bZiA[2];
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_sdCSBPv59coXTEz3qwUXMeA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__SRlIwYUUH1G46Yee9aMIFAQ)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* y);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, at__s2ocO7QwvJg5hna9a9a004sw)(NimStringDesc** a, NI aLen_0);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_l6uHwLXJlTbbc0Q3R9agjwg)(NimStringDesc* cmdline, tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitCharSet)(NimStringDesc* s, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw seps, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result);
N_LIB_PRIVATE N_NIMCALL(void, nextOption_fUds30kiga89a9a6wuOFrkww)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p, NimStringDesc* token, NIM_BOOL allowEmpty);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_6e5MGL10HDAJ205lBYpWxw)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, npo2next)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, npo2cmdLineRest)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg)(NimStringDesc** s, NI sLen_0, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_w3uFmxpwEmgEXFUJjUl10w_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_n0GV8cT30u289bzvb9bOzCmw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_6, "", 0);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_hJtUwp9bs9cZbgrKsWuACD3Q_7 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
NIM_CONST tyArray_1N75LKnZklmK4NsXtZ9bZiA TM_hJtUwp9bs9cZbgrKsWuACD3Q_8 = {58,
61}
;
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_20, "--", 2);
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_22, "-", 1);
STRING_LITERAL(TM_hJtUwp9bs9cZbgrKsWuACD3Q_25, " ", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, initOptParser_sdCSBPv59coXTEz3qwUXMeA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
	nimfr_("initOptParser", "parseopt2.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
	(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
	nimln_(50, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*Result).remainingShortOptions), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
	nimln_(52, "parseopt2.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__SRlIwYUUH1G46Yee9aMIFAQ(cmdline, NIM_NIL);
		if (!T3_) goto LA4_;
		nimln_(53, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*Result).cmd), commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ());
		nimln_(54, "parseopt2.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(58, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*Result).cmd), at__s2ocO7QwvJg5hna9a9a004sw(cmdline->data, cmdline->Sup.len));
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initOptParser_l6uHwLXJlTbbc0Q3R9agjwg)(NimStringDesc* cmdline, tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
	nimfr_("initOptParser", "parseopt2.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
	(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
	nimln_(64, "parseopt2.nim");
	{
		if (!((cmdline) && (cmdline)->Sup.len == 0)) goto LA3_;
		nimln_(65, "parseopt2.nim");
		initOptParser_sdCSBPv59coXTEz3qwUXMeA(NIM_NIL, Result);
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T6_;
		nimln_(67, "parseopt2.nim");
		T6_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		T6_ = nsuSplitCharSet(cmdline, TM_hJtUwp9bs9cZbgrKsWuACD3Q_7, ((NI) -1));
		initOptParser_sdCSBPv59coXTEz3qwUXMeA(T6_, Result);
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initOptParser_7ywjeToZhKr9cLpneviH7zg)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* Result) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T1_;
	nimfr_("initOptParser", "parseopt2.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_w3uFmxpwEmgEXFUJjUl10w_));
	(*Result).Sup.m_type = (&NTI_w3uFmxpwEmgEXFUJjUl10w_);
	nimln_(72, "parseopt2.nim");
	T1_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T1_ = commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ();
	initOptParser_sdCSBPv59coXTEz3qwUXMeA(T1_, Result);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_9;
	NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_10;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3556, "system.nim");
	a = x.a;
	nimln_(3557, "system.nim");
	nimln_(3546, "system.nim");
	TM_hJtUwp9bs9cZbgrKsWuACD3Q_9 = subInt(x.b, a);
	TM_hJtUwp9bs9cZbgrKsWuACD3Q_10 = addInt((NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_9), ((NI) 1));
	L = (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_10);
	nimln_(3558, "system.nim");
	result = mnewString(((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_11;
				NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_12;
				if (!(i_2 < L)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(3559, "system.nim");
				TM_hJtUwp9bs9cZbgrKsWuACD3Q_11 = addInt(i, a);
				if ((NU)((NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_11)) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i] = s->data[(NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_11)];
				nimln_(3522, "system.nim");
				TM_hJtUwp9bs9cZbgrKsWuACD3Q_12 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_12);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, nextOption_fUds30kiga89a9a6wuOFrkww)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p, NimStringDesc* token, NIM_BOOL allowEmpty) {
	nimfr_("nextOption", "parseopt2.nim");
{	{
		NIM_CHAR splitchar;
		NI i;
		splitchar = (NIM_CHAR)0;
		nimln_(2199, "system.nim");
		i = ((NI) 0);
		nimln_(2200, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 1))) goto LA4_;
			{
				nimln_(2201, "system.nim");
				while (1) {
					NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_16;
					nimln_(2202, "system.nim");
					splitchar = TM_hJtUwp9bs9cZbgrKsWuACD3Q_8[(i)- 0];
					nimln_(78, "parseopt2.nim");
					{
						NIM_BOOL T10_;
						NI pos;
						NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_13;
						tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T13_;
						NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_14;
						NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_15;
						tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T14_;
						T10_ = (NIM_BOOL)0;
						T10_ = contains_6e5MGL10HDAJ205lBYpWxw(token, splitchar);
						if (!T10_) goto LA11_;
						nimln_(79, "parseopt2.nim");
						pos = nsuFindChar(token, splitchar, ((NI) 0), ((NI) 0));
						nimln_(80, "parseopt2.nim");
						TM_hJtUwp9bs9cZbgrKsWuACD3Q_13 = subInt(pos, ((NI) 1));
						T13_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 0), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_13));
						unsureAsgnRef((void**) (&(*p).key), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(token, T13_));
						nimln_(81, "parseopt2.nim");
						TM_hJtUwp9bs9cZbgrKsWuACD3Q_14 = addInt(pos, ((NI) 1));
						TM_hJtUwp9bs9cZbgrKsWuACD3Q_15 = subInt((token ? token->Sup.len : 0), ((NI) 1));
						T14_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes((NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_14), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_15));
						unsureAsgnRef((void**) (&(*p).val), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(token, T14_));
						nimln_(82, "parseopt2.nim");
						goto BeforeRet_;
					}
					LA11_: ;
					nimln_(2203, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i)))) goto LA17_;
						goto LA6;
					}
					LA17_: ;
					nimln_(2204, "system.nim");
					TM_hJtUwp9bs9cZbgrKsWuACD3Q_16 = addInt(i, ((NI) 1));
					if (TM_hJtUwp9bs9cZbgrKsWuACD3Q_16 < 0 || TM_hJtUwp9bs9cZbgrKsWuACD3Q_16 > 1) raiseOverflow();
					i = (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_16);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	nimln_(84, "parseopt2.nim");
	unsureAsgnRef((void**) (&(*p).key), copyString(token));
	nimln_(85, "parseopt2.nim");
	{
		if (!allowEmpty) goto LA21_;
		nimln_(86, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
	}
	goto LA19_;
	LA21_: ;
	{
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_17;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T24_;
		nimln_(88, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_17 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		T24_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 0), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_17));
		unsureAsgnRef((void**) (&(*p).remainingShortOptions), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(token, T24_));
		nimln_(89, "parseopt2.nim");
		npo2next(p);
	}
	LA19_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, npo2next)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p) {
	NimStringDesc* token;
	NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_19;
	nimfr_("next", "parseopt2.nim");
{	nimln_(92, "parseopt2.nim");
	{
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T5_;
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_18;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T6_;
		nimln_(398, "system.nim");
		nimln_(92, "parseopt2.nim");
		if (!!((((*p).remainingShortOptions ? (*p).remainingShortOptions->Sup.len : 0) == ((NI) 0)))) goto LA3_;
		nimln_(93, "parseopt2.nim");
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3);
		nimln_(94, "parseopt2.nim");
		T5_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 0), ((NI) 0));
		unsureAsgnRef((void**) (&(*p).key), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*p).remainingShortOptions, T5_));
		nimln_(95, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
		nimln_(96, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_18 = subInt(((*p).remainingShortOptions ? (*p).remainingShortOptions->Sup.len : 0), ((NI) 1));
		T6_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 1), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_18));
		unsureAsgnRef((void**) (&(*p).remainingShortOptions), X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*p).remainingShortOptions, T6_));
		nimln_(97, "parseopt2.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(99, "parseopt2.nim");
	{
		NI T9_;
		T9_ = ((*p).cmd ? (*p).cmd->Sup.len : 0);
		if (!(T9_ <= (*p).pos)) goto LA10_;
		nimln_(100, "parseopt2.nim");
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 0);
		nimln_(101, "parseopt2.nim");
		goto BeforeRet_;
	}
	LA10_: ;
	nimln_(103, "parseopt2.nim");
	if ((NU)((*p).pos) >= (NU)((*p).cmd->Sup.len)) raiseIndexError();
	token = (*p).cmd->data[(*p).pos];
	nimln_(104, "parseopt2.nim");
	TM_hJtUwp9bs9cZbgrKsWuACD3Q_19 = addInt((*p).pos, ((NI) 1));
	(*p).pos = (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_19);
	nimln_(106, "parseopt2.nim");
	{
		NIM_BOOL T14_;
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_21;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T17_;
		NimStringDesc* T18_;
		T14_ = (NIM_BOOL)0;
		T14_ = nsuStartsWith(token, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_20));
		if (!T14_) goto LA15_;
		nimln_(107, "parseopt2.nim");
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 2);
		nimln_(108, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_21 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		T17_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 2), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_21));
		T18_ = (NimStringDesc*)0;
		T18_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(token, T17_);
		nextOption_fUds30kiga89a9a6wuOFrkww(p, T18_, NIM_TRUE);
	}
	goto LA12_;
	LA15_: ;
	{
		NIM_BOOL T20_;
		NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_23;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T23_;
		NimStringDesc* T24_;
		nimln_(109, "parseopt2.nim");
		T20_ = (NIM_BOOL)0;
		T20_ = nsuStartsWith(token, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_22));
		if (!T20_) goto LA21_;
		nimln_(110, "parseopt2.nim");
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 3);
		nimln_(111, "parseopt2.nim");
		TM_hJtUwp9bs9cZbgrKsWuACD3Q_23 = subInt((token ? token->Sup.len : 0), ((NI) 1));
		T23_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 1), (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_23));
		T24_ = (NimStringDesc*)0;
		T24_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(token, T23_);
		nextOption_fUds30kiga89a9a6wuOFrkww(p, T24_, NIM_TRUE);
	}
	goto LA12_;
	LA21_: ;
	{
		nimln_(113, "parseopt2.nim");
		(*p).kind = ((tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw) 1);
		nimln_(114, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).key), copyString(token));
		nimln_(115, "parseopt2.nim");
		unsureAsgnRef((void**) (&(*p).val), copyString(((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_6)));
	}
	LA12_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, npo2cmdLineRest)(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w* p) {
	NimStringDesc* result;
	NI T1_;
	NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_24;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T2_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T3_;
	nimfr_("cmdLineRest", "parseopt2.nim");
{	result = (NimStringDesc*)0;
	nimln_(120, "parseopt2.nim");
	T1_ = ((*p).cmd ? (*p).cmd->Sup.len : 0);
	TM_hJtUwp9bs9cZbgrKsWuACD3Q_24 = subInt(T1_, ((NI) 1));
	T2_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes((*p).pos, (NI)(TM_hJtUwp9bs9cZbgrKsWuACD3Q_24));
	T3_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T3_ = X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg((*p).cmd->data, (*p).cmd->Sup.len, T2_);
	result = nsuJoinSep(T3_->data, T3_->Sup.len, ((NimStringDesc*) &TM_hJtUwp9bs9cZbgrKsWuACD3Q_25));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2Init000)(void) {
	nimfr_("parseopt2", "parseopt2.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseopt2DatInit000)(void) {
static TNimNode* TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[6];
static TNimNode* TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[4];
NI TM_hJtUwp9bs9cZbgrKsWuACD3Q_5;
static char* NIM_CONST TM_hJtUwp9bs9cZbgrKsWuACD3Q_4[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[12];
NTI_w3uFmxpwEmgEXFUJjUl10w_.size = sizeof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w);
NTI_w3uFmxpwEmgEXFUJjUl10w_.kind = 17;
NTI_w3uFmxpwEmgEXFUJjUl10w_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[0] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, cmd);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[1].name = "cmd";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[1] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, pos);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[2].name = "pos";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[2] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, remainingShortOptions);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[3].name = "remainingShortOptions";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[3] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4];
NTI_n0GV8cT30u289bzvb9bOzCmw_.size = sizeof(tyEnum_CmdLineKind_n0GV8cT30u289bzvb9bOzCmw);
NTI_n0GV8cT30u289bzvb9bOzCmw_.kind = 14;
NTI_n0GV8cT30u289bzvb9bOzCmw_.base = 0;
NTI_n0GV8cT30u289bzvb9bOzCmw_.flags = 3;
for (TM_hJtUwp9bs9cZbgrKsWuACD3Q_5 = 0; TM_hJtUwp9bs9cZbgrKsWuACD3Q_5 < 4; TM_hJtUwp9bs9cZbgrKsWuACD3Q_5++) {
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5].offset = TM_hJtUwp9bs9cZbgrKsWuACD3Q_5;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5].name = TM_hJtUwp9bs9cZbgrKsWuACD3Q_4[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[TM_hJtUwp9bs9cZbgrKsWuACD3Q_5+5];
}
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].len = 4; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].kind = 2; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9].sons = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_3[0];
NTI_n0GV8cT30u289bzvb9bOzCmw_.node = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[9];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, kind);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].typ = (&NTI_n0GV8cT30u289bzvb9bOzCmw_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[4].name = "kind";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[4] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, key);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[10].name = "key";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[5] = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11];
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].kind = 1;
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].offset = offsetof(tyObject_OptParser_w3uFmxpwEmgEXFUJjUl10w, val);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[11].name = "val";
TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].len = 6; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].kind = 2; TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0].sons = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_2[0];
NTI_w3uFmxpwEmgEXFUJjUl10w_.node = &TM_hJtUwp9bs9cZbgrKsWuACD3Q_0[0];
}

