/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/coop/Projects/nim/tic_tac_toe/nimcache/stdlib_parseopt.o /home/coop/Projects/nim/tic_tac_toe/nimcache/stdlib_parseopt.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA;
struct tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA {
  RootObj Sup;
NimStringDesc* cmd;
NI pos;
NIM_BOOL inShortState;
tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA kind;
NimStringDesc* key;
NimStringDesc* val;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, parseWord_JAw9bP8tjPXKSullchoBwUA)(NimStringDesc* s, NI i, NimStringDesc** w, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw delim);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, quote_yY2O2tPIqumYuvhyVZH8Zg)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars, NI start, NI last);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_xt25Cv9cQqaNt3Mscl7nHFA)(NimStringDesc* cmdline, tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_39aUkhGW9bGoDuN4JvXreV8Q)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* Result);
N_LIB_PRIVATE N_NIMCALL(void, handleShortOption_7aIl9cJUX5tPqtQBG33k9aMg)(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* p);
N_LIB_PRIVATE N_NIMCALL(void, nponext)(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* p);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, npocmdLineRest)(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* p);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_fe5bDDfRbVwQIuUOouExnA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_XkdXq9atxjiuhkFFh0XYrSA_;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_GYgvYKeHVTEls0AcywABHQ_6 = {
0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_GYgvYKeHVTEls0AcywABHQ_7 = {
0x01, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x24,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_GYgvYKeHVTEls0AcywABHQ_14, "", 0);
STRING_LITERAL(TM_GYgvYKeHVTEls0AcywABHQ_16, "", 0);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_GYgvYKeHVTEls0AcywABHQ_23 = {
0x01, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_GYgvYKeHVTEls0AcywABHQ_31 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, parseWord_JAw9bP8tjPXKSullchoBwUA)(NimStringDesc* s, NI i, NimStringDesc** w, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw delim) {
	NI result;
	nimfr_("parseWord", "parseopt.nim");
	result = (NI)0;
	nimln_(47, "parseopt.nim");
	result = i;
	nimln_(48, "parseopt.nim");
	{
		NI TM_GYgvYKeHVTEls0AcywABHQ_2;
		if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[result]) == (NU8)(34))) goto LA3_;
		nimln_(49, "parseopt.nim");
		TM_GYgvYKeHVTEls0AcywABHQ_2 = addInt(result, ((NI) 1));
		result = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_2);
		{
			nimln_(50, "parseopt.nim");
			while (1) {
				NI TM_GYgvYKeHVTEls0AcywABHQ_3;
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!((((NU8)(s->data[result])) == ((NU8)(0)) || ((NU8)(s->data[result])) == ((NU8)(34))))) goto LA6;
				nimln_(51, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				(*w) = addChar((*w), s->data[result]);
				nimln_(52, "parseopt.nim");
				TM_GYgvYKeHVTEls0AcywABHQ_3 = addInt(result, ((NI) 1));
				result = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_3);
			} LA6: ;
		}
		nimln_(53, "parseopt.nim");
		{
			NI TM_GYgvYKeHVTEls0AcywABHQ_4;
			if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((NU8)(s->data[result]) == (NU8)(34))) goto LA9_;
			TM_GYgvYKeHVTEls0AcywABHQ_4 = addInt(result, ((NI) 1));
			result = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_4);
		}
		LA9_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		{
			nimln_(55, "parseopt.nim");
			while (1) {
				NI TM_GYgvYKeHVTEls0AcywABHQ_5;
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!(((delim[(NU)(((NU8)(s->data[result])))>>3] &(1U<<((NU)(((NU8)(s->data[result])))&7U)))!=0))) goto LA13;
				nimln_(56, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				(*w) = addChar((*w), s->data[result]);
				nimln_(57, "parseopt.nim");
				TM_GYgvYKeHVTEls0AcywABHQ_5 = addInt(result, ((NI) 1));
				result = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_5);
			} LA13: ;
		}
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, quote_yY2O2tPIqumYuvhyVZH8Zg)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr_("quote", "parseopt.nim");
	result = (NimStringDesc*)0;
	nimln_(61, "parseopt.nim");
	{
		NIM_BOOL T3_;
		NI T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NI)0;
		T4_ = nsuFindCharSet(s, TM_GYgvYKeHVTEls0AcywABHQ_6, ((NI) 0), ((NI) 0));
		T3_ = (((NI) 0) <= T4_);
		if (!(T3_)) goto LA5_;
		nimln_(398, "system.nim");
		nimln_(61, "parseopt.nim");
		if ((NU)(((NI) 0)) > (NU)(s->Sup.len)) raiseIndexError();
		T3_ = !(((NU8)(s->data[((NI) 0)]) == (NU8)(34)));
		LA5_: ;
		if (!T3_) goto LA6_;
		nimln_(62, "parseopt.nim");
		{
			NI i;
			if ((NU)(((NI) 0)) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((NU8)(s->data[((NI) 0)]) == (NU8)(45))) goto LA10_;
			nimln_(63, "parseopt.nim");
			result = rawNewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
			nimln_(64, "parseopt.nim");
			i = parseWord_JAw9bP8tjPXKSullchoBwUA(s, ((NI) 0), (&result), TM_GYgvYKeHVTEls0AcywABHQ_7);
			nimln_(65, "parseopt.nim");
			{
				NI TM_GYgvYKeHVTEls0AcywABHQ_8;
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!(((NU8)(s->data[i])) == ((NU8)(58)) || ((NU8)(s->data[i])) == ((NU8)(61)))) goto LA14_;
				nimln_(66, "parseopt.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				result = addChar(result, s->data[i]);
				nimln_(67, "parseopt.nim");
				TM_GYgvYKeHVTEls0AcywABHQ_8 = addInt(i, ((NI) 1));
				i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_8);
			}
			LA14_: ;
			nimln_(68, "parseopt.nim");
			result = addChar(result, 34);
			{
				nimln_(69, "parseopt.nim");
				while (1) {
					NI TM_GYgvYKeHVTEls0AcywABHQ_9;
					if (!(i < (s ? s->Sup.len : 0))) goto LA17;
					nimln_(70, "parseopt.nim");
					if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
					result = addChar(result, s->data[i]);
					nimln_(71, "parseopt.nim");
					TM_GYgvYKeHVTEls0AcywABHQ_9 = addInt(i, ((NI) 1));
					i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_9);
				} LA17: ;
			}
			nimln_(72, "parseopt.nim");
			result = addChar(result, 34);
		}
		goto LA8_;
		LA10_: ;
		{
			NimStringDesc* T19_;
			nimln_(74, "parseopt.nim");
			T19_ = (NimStringDesc*)0;
			T19_ = rawNewString(s->Sup.len + 2);
appendChar(T19_, 34);
appendString(T19_, s);
appendChar(T19_, 34);
			result = T19_;
		}
		LA8_: ;
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(76, "parseopt.nim");
		result = copyString(s);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initOptParser_xt25Cv9cQqaNt3Mscl7nHFA)(NimStringDesc* cmdline, tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* Result) {
	nimfr_("initOptParser", "parseopt.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_fe5bDDfRbVwQIuUOouExnA_));
	(*Result).Sup.m_type = (&NTI_fe5bDDfRbVwQIuUOouExnA_);
	nimln_(84, "parseopt.nim");
	(*Result).pos = ((NI) 0);
	nimln_(85, "parseopt.nim");
	(*Result).inShortState = NIM_FALSE;
	nimln_(86, "parseopt.nim");
	{
		nimln_(398, "system.nim");
		nimln_(86, "parseopt.nim");
		if (!!(((cmdline) && (cmdline)->Sup.len == 0))) goto LA3_;
		nimln_(87, "parseopt.nim");
		unsureAsgnRef((void**) (&(*Result).cmd), copyString(cmdline));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(89, "parseopt.nim");
		unsureAsgnRef((void**) (&(*Result).cmd), copyString(((NimStringDesc*) &TM_GYgvYKeHVTEls0AcywABHQ_14)));
		{
			NI i;
			NI colontmp_;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(90, "parseopt.nim");
			colontmp_ = paramCount_T74rCHY8RMV0X07YnKmggw();
			nimln_(2032, "system.nim");
			res = ((NI) 1);
			{
				nimln_(2033, "system.nim");
				while (1) {
					NimStringDesc* T9_;
					NimStringDesc* T10_;
					NI TM_GYgvYKeHVTEls0AcywABHQ_15;
					if (!(res <= colontmp_)) goto LA8;
					nimln_(2034, "system.nim");
					i = res;
					nimln_(91, "parseopt.nim");
					T9_ = (NimStringDesc*)0;
					T9_ = paramStr_eYicl3uwirn1ppNz7OCowg(i);
					T10_ = (NimStringDesc*)0;
					T10_ = quote_yY2O2tPIqumYuvhyVZH8Zg(T9_);
					(*Result).cmd = resizeString((*Result).cmd, T10_->Sup.len + 0);
appendString((*Result).cmd, T10_);
					nimln_(92, "parseopt.nim");
					(*Result).cmd = addChar((*Result).cmd, 32);
					nimln_(2035, "system.nim");
					TM_GYgvYKeHVTEls0AcywABHQ_15 = addInt(res, ((NI) 1));
					res = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_15);
				} LA8: ;
			}
		}
	}
	LA1_: ;
	nimln_(93, "parseopt.nim");
	(*Result).kind = ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 0);
	nimln_(94, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).key), copyString(((NimStringDesc*) &TM_GYgvYKeHVTEls0AcywABHQ_16)));
	nimln_(95, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).val), copyString(((NimStringDesc*) &TM_GYgvYKeHVTEls0AcywABHQ_16)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initOptParser_39aUkhGW9bGoDuN4JvXreV8Q)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cmdline, tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* Result) {
	nimfr_("initOptParser", "parseopt.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_fe5bDDfRbVwQIuUOouExnA_));
	(*Result).Sup.m_type = (&NTI_fe5bDDfRbVwQIuUOouExnA_);
	nimln_(100, "parseopt.nim");
	(*Result).pos = ((NI) 0);
	nimln_(101, "parseopt.nim");
	(*Result).inShortState = NIM_FALSE;
	nimln_(102, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).cmd), copyString(((NimStringDesc*) &TM_GYgvYKeHVTEls0AcywABHQ_14)));
	nimln_(103, "parseopt.nim");
	{
		NI T3_;
		nimln_(398, "system.nim");
		nimln_(103, "parseopt.nim");
		T3_ = (cmdline ? cmdline->Sup.len : 0);
		if (!!((T3_ == ((NI) 0)))) goto LA4_;
		{
			NI i;
			NI colontmp_;
			NI T7_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(104, "parseopt.nim");
			T7_ = (cmdline ? cmdline->Sup.len : 0);
			colontmp_ = T7_;
			nimln_(3519, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NimStringDesc* T10_;
					NI TM_GYgvYKeHVTEls0AcywABHQ_17;
					if (!(i_2 < colontmp_)) goto LA9;
					nimln_(3521, "system.nim");
					i = i_2;
					nimln_(105, "parseopt.nim");
					if ((NU)(i) >= (NU)(cmdline->Sup.len)) raiseIndexError();
					T10_ = (NimStringDesc*)0;
					T10_ = quote_yY2O2tPIqumYuvhyVZH8Zg(cmdline->data[i]);
					(*Result).cmd = resizeString((*Result).cmd, T10_->Sup.len + 0);
appendString((*Result).cmd, T10_);
					nimln_(106, "parseopt.nim");
					(*Result).cmd = addChar((*Result).cmd, 32);
					nimln_(3522, "system.nim");
					TM_GYgvYKeHVTEls0AcywABHQ_17 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_17);
				} LA9: ;
			}
		}
	}
	goto LA1_;
	LA4_: ;
	{
		{
			NI i_3;
			NI colontmp__2;
			NI res;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(108, "parseopt.nim");
			colontmp__2 = paramCount_T74rCHY8RMV0X07YnKmggw();
			nimln_(2032, "system.nim");
			res = ((NI) 1);
			{
				nimln_(2033, "system.nim");
				while (1) {
					NimStringDesc* T15_;
					NimStringDesc* T16_;
					NI TM_GYgvYKeHVTEls0AcywABHQ_18;
					if (!(res <= colontmp__2)) goto LA14;
					nimln_(2034, "system.nim");
					i_3 = res;
					nimln_(109, "parseopt.nim");
					T15_ = (NimStringDesc*)0;
					T15_ = paramStr_eYicl3uwirn1ppNz7OCowg(i_3);
					T16_ = (NimStringDesc*)0;
					T16_ = quote_yY2O2tPIqumYuvhyVZH8Zg(T15_);
					(*Result).cmd = resizeString((*Result).cmd, T16_->Sup.len + 0);
appendString((*Result).cmd, T16_);
					nimln_(110, "parseopt.nim");
					(*Result).cmd = addChar((*Result).cmd, 32);
					nimln_(2035, "system.nim");
					TM_GYgvYKeHVTEls0AcywABHQ_18 = addInt(res, ((NI) 1));
					res = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_18);
				} LA14: ;
			}
		}
	}
	LA1_: ;
	nimln_(111, "parseopt.nim");
	(*Result).kind = ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 0);
	nimln_(112, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).key), copyString(((NimStringDesc*) &TM_GYgvYKeHVTEls0AcywABHQ_16)));
	nimln_(113, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).val), copyString(((NimStringDesc*) &TM_GYgvYKeHVTEls0AcywABHQ_16)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, handleShortOption_7aIl9cJUX5tPqtQBG33k9aMg)(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* p) {
	NI i;
	NI TM_GYgvYKeHVTEls0AcywABHQ_19;
	nimfr_("handleShortOption", "parseopt.nim");
	nimln_(116, "parseopt.nim");
	i = (*p).pos;
	nimln_(117, "parseopt.nim");
	(*p).kind = ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 3);
	nimln_(118, "parseopt.nim");
	if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
	(*p).key = addChar((*p).key, (*p).cmd->data[i]);
	nimln_(119, "parseopt.nim");
	TM_GYgvYKeHVTEls0AcywABHQ_19 = addInt(i, ((NI) 1));
	i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_19);
	nimln_(120, "parseopt.nim");
	(*p).inShortState = NIM_TRUE;
	{
		nimln_(121, "parseopt.nim");
		while (1) {
			NI TM_GYgvYKeHVTEls0AcywABHQ_20;
			if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
			if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA2;
			nimln_(122, "parseopt.nim");
			TM_GYgvYKeHVTEls0AcywABHQ_20 = addInt(i, ((NI) 1));
			i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_20);
			nimln_(123, "parseopt.nim");
			(*p).inShortState = NIM_FALSE;
		} LA2: ;
	}
	nimln_(124, "parseopt.nim");
	{
		NI TM_GYgvYKeHVTEls0AcywABHQ_21;
		if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
		if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(58)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(61)))) goto LA5_;
		nimln_(125, "parseopt.nim");
		TM_GYgvYKeHVTEls0AcywABHQ_21 = addInt(i, ((NI) 1));
		i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_21);
		nimln_(126, "parseopt.nim");
		(*p).inShortState = NIM_FALSE;
		{
			nimln_(127, "parseopt.nim");
			while (1) {
				NI TM_GYgvYKeHVTEls0AcywABHQ_22;
				if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
				if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA8;
				TM_GYgvYKeHVTEls0AcywABHQ_22 = addInt(i, ((NI) 1));
				i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_22);
			} LA8: ;
		}
		nimln_(128, "parseopt.nim");
		i = parseWord_JAw9bP8tjPXKSullchoBwUA((*p).cmd, i, (&(*p).val), TM_GYgvYKeHVTEls0AcywABHQ_23);
	}
	LA5_: ;
	nimln_(129, "parseopt.nim");
	{
		if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
		if (!((NU8)((*p).cmd->data[i]) == (NU8)(0))) goto LA11_;
		(*p).inShortState = NIM_FALSE;
	}
	LA11_: ;
	nimln_(130, "parseopt.nim");
	(*p).pos = i;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, nponext)(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* p) {
	NI i;
	nimfr_("next", "parseopt.nim");
{	nimln_(135, "parseopt.nim");
	i = (*p).pos;
	{
		nimln_(136, "parseopt.nim");
		while (1) {
			NI TM_GYgvYKeHVTEls0AcywABHQ_24;
			if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
			if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA2;
			TM_GYgvYKeHVTEls0AcywABHQ_24 = addInt(i, ((NI) 1));
			i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_24);
		} LA2: ;
	}
	nimln_(137, "parseopt.nim");
	(*p).pos = i;
	nimln_(138, "parseopt.nim");
	(*p).key = setLengthStr((*p).key, ((NI) 0));
	nimln_(139, "parseopt.nim");
	(*p).val = setLengthStr((*p).val, ((NI) 0));
	nimln_(140, "parseopt.nim");
	{
		if (!(*p).inShortState) goto LA5_;
		nimln_(141, "parseopt.nim");
		handleShortOption_7aIl9cJUX5tPqtQBG33k9aMg(p);
		nimln_(142, "parseopt.nim");
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(143, "parseopt.nim");
	if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
	switch (((NU8)((*p).cmd->data[i]))) {
	case 0:
	{
		nimln_(145, "parseopt.nim");
		(*p).kind = ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 0);
	}
	break;
	case 45:
	{
		NI TM_GYgvYKeHVTEls0AcywABHQ_25;
		nimln_(147, "parseopt.nim");
		TM_GYgvYKeHVTEls0AcywABHQ_25 = addInt(i, ((NI) 1));
		i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_25);
		nimln_(148, "parseopt.nim");
		{
			NI TM_GYgvYKeHVTEls0AcywABHQ_26;
			if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
			if (!((NU8)((*p).cmd->data[i]) == (NU8)(45))) goto LA11_;
			nimln_(149, "parseopt.nim");
			(*p).kind = ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 2);
			nimln_(150, "parseopt.nim");
			TM_GYgvYKeHVTEls0AcywABHQ_26 = addInt(i, ((NI) 1));
			i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_26);
			nimln_(151, "parseopt.nim");
			i = parseWord_JAw9bP8tjPXKSullchoBwUA((*p).cmd, i, (&(*p).key), TM_GYgvYKeHVTEls0AcywABHQ_7);
			{
				nimln_(152, "parseopt.nim");
				while (1) {
					NI TM_GYgvYKeHVTEls0AcywABHQ_27;
					if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
					if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA14;
					TM_GYgvYKeHVTEls0AcywABHQ_27 = addInt(i, ((NI) 1));
					i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_27);
				} LA14: ;
			}
			nimln_(153, "parseopt.nim");
			{
				NI TM_GYgvYKeHVTEls0AcywABHQ_28;
				if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
				if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(58)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(61)))) goto LA17_;
				nimln_(154, "parseopt.nim");
				TM_GYgvYKeHVTEls0AcywABHQ_28 = addInt(i, ((NI) 1));
				i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_28);
				{
					nimln_(155, "parseopt.nim");
					while (1) {
						NI TM_GYgvYKeHVTEls0AcywABHQ_29;
						if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
						if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA20;
						TM_GYgvYKeHVTEls0AcywABHQ_29 = addInt(i, ((NI) 1));
						i = (NI)(TM_GYgvYKeHVTEls0AcywABHQ_29);
					} LA20: ;
				}
				nimln_(156, "parseopt.nim");
				(*p).pos = parseWord_JAw9bP8tjPXKSullchoBwUA((*p).cmd, i, (&(*p).val), TM_GYgvYKeHVTEls0AcywABHQ_23);
			}
			goto LA15_;
			LA17_: ;
			{
				nimln_(158, "parseopt.nim");
				(*p).pos = i;
			}
			LA15_: ;
		}
		goto LA9_;
		LA11_: ;
		{
			nimln_(160, "parseopt.nim");
			(*p).pos = i;
			nimln_(161, "parseopt.nim");
			handleShortOption_7aIl9cJUX5tPqtQBG33k9aMg(p);
		}
		LA9_: ;
	}
	break;
	default:
	{
		nimln_(163, "parseopt.nim");
		(*p).kind = ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 1);
		nimln_(164, "parseopt.nim");
		(*p).pos = parseWord_JAw9bP8tjPXKSullchoBwUA((*p).cmd, i, (&(*p).key), TM_GYgvYKeHVTEls0AcywABHQ_23);
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, npocmdLineRest)(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* p) {
	NimStringDesc* result;
	NI TM_GYgvYKeHVTEls0AcywABHQ_30;
	NimStringDesc* T1_;
	nimfr_("cmdLineRest", "parseopt.nim");
	result = (NimStringDesc*)0;
	nimln_(168, "parseopt.nim");
	TM_GYgvYKeHVTEls0AcywABHQ_30 = subInt(((*p).cmd ? (*p).cmd->Sup.len : 0), ((NI) 1));
	T1_ = (NimStringDesc*)0;
	T1_ = copyStrLast((*p).cmd, (*p).pos, (NI)(TM_GYgvYKeHVTEls0AcywABHQ_30));
	result = nsuStrip(T1_, NIM_TRUE, NIM_TRUE, TM_GYgvYKeHVTEls0AcywABHQ_31);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseoptInit000)(void) {
	nimfr_("parseopt", "parseopt.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseoptDatInit000)(void) {
static TNimNode* TM_GYgvYKeHVTEls0AcywABHQ_10[6];
static TNimNode* TM_GYgvYKeHVTEls0AcywABHQ_11[4];
NI TM_GYgvYKeHVTEls0AcywABHQ_13;
static char* NIM_CONST TM_GYgvYKeHVTEls0AcywABHQ_12[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode TM_GYgvYKeHVTEls0AcywABHQ_0[12];
NTI_fe5bDDfRbVwQIuUOouExnA_.size = sizeof(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA);
NTI_fe5bDDfRbVwQIuUOouExnA_.kind = 17;
NTI_fe5bDDfRbVwQIuUOouExnA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_GYgvYKeHVTEls0AcywABHQ_10[0] = &TM_GYgvYKeHVTEls0AcywABHQ_0[1];
TM_GYgvYKeHVTEls0AcywABHQ_0[1].kind = 1;
TM_GYgvYKeHVTEls0AcywABHQ_0[1].offset = offsetof(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA, cmd);
TM_GYgvYKeHVTEls0AcywABHQ_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_GYgvYKeHVTEls0AcywABHQ_0[1].name = "cmd";
TM_GYgvYKeHVTEls0AcywABHQ_10[1] = &TM_GYgvYKeHVTEls0AcywABHQ_0[2];
TM_GYgvYKeHVTEls0AcywABHQ_0[2].kind = 1;
TM_GYgvYKeHVTEls0AcywABHQ_0[2].offset = offsetof(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA, pos);
TM_GYgvYKeHVTEls0AcywABHQ_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_GYgvYKeHVTEls0AcywABHQ_0[2].name = "pos";
TM_GYgvYKeHVTEls0AcywABHQ_10[2] = &TM_GYgvYKeHVTEls0AcywABHQ_0[3];
TM_GYgvYKeHVTEls0AcywABHQ_0[3].kind = 1;
TM_GYgvYKeHVTEls0AcywABHQ_0[3].offset = offsetof(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA, inShortState);
TM_GYgvYKeHVTEls0AcywABHQ_0[3].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_GYgvYKeHVTEls0AcywABHQ_0[3].name = "inShortState";
TM_GYgvYKeHVTEls0AcywABHQ_10[3] = &TM_GYgvYKeHVTEls0AcywABHQ_0[4];
NTI_XkdXq9atxjiuhkFFh0XYrSA_.size = sizeof(tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA);
NTI_XkdXq9atxjiuhkFFh0XYrSA_.kind = 14;
NTI_XkdXq9atxjiuhkFFh0XYrSA_.base = 0;
NTI_XkdXq9atxjiuhkFFh0XYrSA_.flags = 3;
for (TM_GYgvYKeHVTEls0AcywABHQ_13 = 0; TM_GYgvYKeHVTEls0AcywABHQ_13 < 4; TM_GYgvYKeHVTEls0AcywABHQ_13++) {
TM_GYgvYKeHVTEls0AcywABHQ_0[TM_GYgvYKeHVTEls0AcywABHQ_13+5].kind = 1;
TM_GYgvYKeHVTEls0AcywABHQ_0[TM_GYgvYKeHVTEls0AcywABHQ_13+5].offset = TM_GYgvYKeHVTEls0AcywABHQ_13;
TM_GYgvYKeHVTEls0AcywABHQ_0[TM_GYgvYKeHVTEls0AcywABHQ_13+5].name = TM_GYgvYKeHVTEls0AcywABHQ_12[TM_GYgvYKeHVTEls0AcywABHQ_13];
TM_GYgvYKeHVTEls0AcywABHQ_11[TM_GYgvYKeHVTEls0AcywABHQ_13] = &TM_GYgvYKeHVTEls0AcywABHQ_0[TM_GYgvYKeHVTEls0AcywABHQ_13+5];
}
TM_GYgvYKeHVTEls0AcywABHQ_0[9].len = 4; TM_GYgvYKeHVTEls0AcywABHQ_0[9].kind = 2; TM_GYgvYKeHVTEls0AcywABHQ_0[9].sons = &TM_GYgvYKeHVTEls0AcywABHQ_11[0];
NTI_XkdXq9atxjiuhkFFh0XYrSA_.node = &TM_GYgvYKeHVTEls0AcywABHQ_0[9];
TM_GYgvYKeHVTEls0AcywABHQ_0[4].kind = 1;
TM_GYgvYKeHVTEls0AcywABHQ_0[4].offset = offsetof(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA, kind);
TM_GYgvYKeHVTEls0AcywABHQ_0[4].typ = (&NTI_XkdXq9atxjiuhkFFh0XYrSA_);
TM_GYgvYKeHVTEls0AcywABHQ_0[4].name = "kind";
TM_GYgvYKeHVTEls0AcywABHQ_10[4] = &TM_GYgvYKeHVTEls0AcywABHQ_0[10];
TM_GYgvYKeHVTEls0AcywABHQ_0[10].kind = 1;
TM_GYgvYKeHVTEls0AcywABHQ_0[10].offset = offsetof(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA, key);
TM_GYgvYKeHVTEls0AcywABHQ_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_GYgvYKeHVTEls0AcywABHQ_0[10].name = "key";
TM_GYgvYKeHVTEls0AcywABHQ_10[5] = &TM_GYgvYKeHVTEls0AcywABHQ_0[11];
TM_GYgvYKeHVTEls0AcywABHQ_0[11].kind = 1;
TM_GYgvYKeHVTEls0AcywABHQ_0[11].offset = offsetof(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA, val);
TM_GYgvYKeHVTEls0AcywABHQ_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_GYgvYKeHVTEls0AcywABHQ_0[11].name = "val";
TM_GYgvYKeHVTEls0AcywABHQ_0[0].len = 6; TM_GYgvYKeHVTEls0AcywABHQ_0[0].kind = 2; TM_GYgvYKeHVTEls0AcywABHQ_0[0].sons = &TM_GYgvYKeHVTEls0AcywABHQ_10[0];
NTI_fe5bDDfRbVwQIuUOouExnA_.node = &TM_GYgvYKeHVTEls0AcywABHQ_0[0];
}

