/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/coop/Projects/nim/tic_tac_toe/nimcache/tic_tac_toe.o /home/coop/Projects/nim/tic_tac_toe/nimcache/tic_tac_toe.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ;
typedef struct tySequence_SFipDZIkFtPcrLs0AGBBjQ tySequence_SFipDZIkFtPcrLs0AGBBjQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_PSP8snSsRoFs9cDiya9bd7UQ tySequence_PSP8snSsRoFs9cDiya9bd7UQ;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw;
typedef struct RootObj RootObj;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q;
typedef struct tySequence_phjbYJtsbOIAYa9be34hhZg tySequence_phjbYJtsbOIAYa9be34hhZg;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A;
typedef struct tySequence_8Np6tlClE5az1CyqZdN19bQ tySequence_8Np6tlClE5az1CyqZdN19bQ;
typedef struct tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA;
typedef struct tyTuple_8ZxhPt1NwfElsJs8zUSV9bg tyTuple_8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ {
tySequence_SFipDZIkFtPcrLs0AGBBjQ* data;
NI counter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef tyTuple_UV3llMMYFckfui8YMBuUZA tyArray_muTWnl2ZUoKx9beoQeYYdeA[2];
struct RootObj {
TNimType* m_type;
};
struct tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw {
  RootObj Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* list;
};
struct tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q {
NIM_BOOL Field0;
NimStringDesc* Field1;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NimStringDesc* x, void* ClE_0);
void* ClE_0;
} tyProc_45NwvjyfIWTGrNWgg5Pcig;
typedef N_CLOSURE_PTR(NIM_BOOL, TM_zcCJBUqT9bHy43IBzmrbcrw_37) (NimStringDesc* x, void* ClE_0);
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A {
  RootObj Sup;
NimStringDesc* currentPlayer;
tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* board;
NimStringDesc* aiPlayer;
NI difficulty;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* x, void* ClE_0);
void* ClE_0;
} tyProc_lRW9cfxqfm1ql4gkxfLReYg;
typedef N_CLOSURE_PTR(NimStringDesc*, TM_zcCJBUqT9bHy43IBzmrbcrw_53) (NimStringDesc* x);
typedef N_CLOSURE_PTR(NimStringDesc*, TM_zcCJBUqT9bHy43IBzmrbcrw_55) (NimStringDesc* x, void* ClE_0);
typedef NimStringDesc* tyArray_24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NU8 tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA;
struct tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA {
  RootObj Sup;
NimStringDesc* cmd;
NI pos;
NIM_BOOL inShortState;
tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA kind;
NimStringDesc* key;
NimStringDesc* val;
};
struct tyTuple_8ZxhPt1NwfElsJs8zUSV9bg {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A {
NU64 a0;
NU64 a1;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_PSP8snSsRoFs9cDiya9bd7UQ {
  TGenericSeq Sup;
  tySequence_qwqHTkRvwhrRyENtudHQ7g* data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_phjbYJtsbOIAYa9be34hhZg {
  TGenericSeq Sup;
  tySequence_sM4lkSb7zS6F7OVMvW9cffQ* data[SEQ_DECL_SIZE];
};
struct tySequence_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
struct tySequence_SFipDZIkFtPcrLs0AGBBjQ {
  TGenericSeq Sup;
  tyTuple_8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, randomize_RtUZt2O8eA6Y5pFWOsdgjg)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_zcCJBUqT9bHy43IBzmrbcrw_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, toTable_aS0SHfzTdtCR7Owy1P12DA)(tyTuple_UV3llMMYFckfui8YMBuUZA* pairs, NI pairsLen_0, tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* Result);
static N_NIMCALL(void, TM_zcCJBUqT9bHy43IBzmrbcrw_6)(void);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw*, newBoard_1fU9a4wtv9aHhliHQffyd16A)(void);
static N_NIMCALL(void, Marker_tyRef_4rGzeMi7MCB0z6Cv3SPX9bA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, done_mWiw9aAF1zaSpbM8WWAOoUQ)(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* this_0, tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, all_d1z5CZM9aJLWjGEe6JKJ0eA)(NimStringDesc** s, NI sLen_0, tyProc_45NwvjyfIWTGrNWgg5Pcig pred);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__SYCl19axYS7qpWNCbnZT1sg)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwtic_tac_toe)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQtic_tac_toe)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__LChgG3UthCXxSHtCKOvdVw)(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* this_0);
static N_NIMCALL(void, Marker_tySequence_phjbYJtsbOIAYa9be34hhZg)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg)(NimStringDesc** s, NI sLen_0, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, emptySpots_Mg7cA0kmgz33yXQ15jA4dA)(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* this_0);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsDigitStr)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt__4KfyMujq4uMvZmUtFDflyw)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ a, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ b);
N_LIB_PRIVATE N_NIMCALL(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A*, newGame_Kd7XrxXB6GMIVqqmW09aeZQ)(NimStringDesc* aiPlayer, NI difficulty);
N_LIB_PRIVATE N_NIMCALL(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A*, new_dGV9bEqtfd9aLwydHC659boag)(void);
static N_NIMCALL(void, Marker_tyRef_O12MqT52KmSXzoh9aR9a6H6A)(void* p, NI op);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, changePlayer_39csks0fo83GFyFbhmv2cMg)(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* this_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, X5BX5D__bdg4B3o8C8pWA8Qu4aZLYg)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, getBestMove_9bRYUKFkYtq9bByPc70XP9b9cw)(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* this_0, tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* board, NimStringDesc* player);
N_LIB_PRIVATE N_NIMCALL(tySequence_8Np6tlClE5az1CyqZdN19bQ*, newSeq_r6F9aBPw1h0wreCPkFTV9ckQ)(NI len);
static N_INLINE(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, map_U6WKGPJMPQQfVVS4uhKywgtic_tac_toe)(NimStringDesc** s, NI sLen_0, tyProc_lRW9cfxqfm1ql4gkxfLReYg op);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, colonanonymous__39bh9c6Htv4m4f54Tc9abE7Mg)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, max_NN3SMNaATnaYmB26AVHTyQ)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ* x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, min_NN3SMNaATnaYmB26AVHTyQ_2)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ* x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(void, startGame_39csks0fo83GFyFbhmv2cMg_2)(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* this_0);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(NI, rand_ZFto5dQROl6EDzKy42ijyA)(NI* a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(void, writeHelp_AL8TA3zYBSG83tMKprIPlw)(void);
N_LIB_PRIVATE N_NIMCALL(void, cli_74KmN19crw4yATb9b6mHZ0Gw)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOptParser_xt25Cv9cQqaNt3Mscl7nHFA)(NimStringDesc* cmdline, tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* Result);
N_LIB_PRIVATE N_NIMCALL(void, nponext)(tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA* p);
N_LIB_PRIVATE N_NIMCALL(void, initTable_Pb6nsyDUqkcuOfIqNGZ04Q)(NI initialSize, tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__CM5QBhJw8HvPuuaSW9c6LyQ)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaugtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_9bBNTfkcWUAIzJYEZbqre3w)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_i52hhunrCCXlXL7airLPUA)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ* t, tySequence_SFipDZIkFtPcrLs0AGBBjQ** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_t4rnRU9ceXEIukTl9b0Ap10Qtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(NI, rand_an9ajRjsC0saLyxF46lqhIw)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
N_LIB_PRIVATE N_NIMCALL(NI, rand_llsvpw3XcUUMY9bBfAwkSMg)(tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A* r, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseoptInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseoptDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, tic_tac_toeDatInit000)(void);
tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ nextPlayer_FD1svfwLer9czwZuWs3nhCA;
extern TNimType NTI_MCOwvEd9cS88yVcSkkw9bO9aQ_;
tySequence_PSP8snSsRoFs9cDiya9bd7UQ* wins_VQ75bJhUsjDd9cVVt6yg5Eg;
extern TNimType NTI_PSP8snSsRoFs9cDiya9bd7UQ_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_79afGQaHRQB5wDrFbwk3Skw_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_4rGzeMi7MCB0z6Cv3SPX9bA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_ubXr9bFCXs9bc35NkwsYmx2Q_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_phjbYJtsbOIAYa9be34hhZg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
TNimType NTI_RWfNK71Zxw13vryRqXAD1A_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_O12MqT52KmSXzoh9aR9a6H6A_;
TNimType NTI_1v9bKyksXWMsm0vNwmZ4EuQ_;
extern TNimType NTI_fe5bDDfRbVwQIuUOouExnA_;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_4, "X", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_5, "O", 1);
NIM_CONST tyArray_muTWnl2ZUoKx9beoQeYYdeA TM_zcCJBUqT9bHy43IBzmrbcrw_3 = {{((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_4),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_5)}
,
{((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_5),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_4)}
}
;
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_8 = {{3, 3}, {((NI) 0),
((NI) 1),
((NI) 2)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_9 = {{3, 3}, {((NI) 3),
((NI) 4),
((NI) 5)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_10 = {{3, 3}, {((NI) 6),
((NI) 7),
((NI) 8)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_11 = {{3, 3}, {((NI) 0),
((NI) 3),
((NI) 6)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_12 = {{3, 3}, {((NI) 1),
((NI) 4),
((NI) 7)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_13 = {{3, 3}, {((NI) 2),
((NI) 5),
((NI) 8)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_14 = {{3, 3}, {((NI) 0),
((NI) 4),
((NI) 8)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} TM_zcCJBUqT9bHy43IBzmrbcrw_15 = {{3, 3}, {((NI) 2),
((NI) 4),
((NI) 6)}};
NIM_CONST struct {
  TGenericSeq Sup;
  tySequence_qwqHTkRvwhrRyENtudHQ7g* data[8];
} TM_zcCJBUqT9bHy43IBzmrbcrw_16 = {{8, 8}, {((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_8),
((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_9),
((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_10),
((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_11),
((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_12),
((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_13),
((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_14),
((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_zcCJBUqT9bHy43IBzmrbcrw_15)}};
NIM_CONST tySequence_PSP8snSsRoFs9cDiya9bd7UQ* TM_zcCJBUqT9bHy43IBzmrbcrw_7 = ((tySequence_PSP8snSsRoFs9cDiya9bd7UQ*)&TM_zcCJBUqT9bHy43IBzmrbcrw_16);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_18, "0", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_19, "1", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_20, "2", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_21, "3", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_22, "4", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_23, "5", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_24, "6", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_25, "7", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_26, "8", 1);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[9];
} TM_zcCJBUqT9bHy43IBzmrbcrw_27 = {{9, 9}, {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_18),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_19),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_20),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_21),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_22),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_23),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_24),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_25),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_26)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_zcCJBUqT9bHy43IBzmrbcrw_17 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_zcCJBUqT9bHy43IBzmrbcrw_27);
NIM_CONST tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q TM_zcCJBUqT9bHy43IBzmrbcrw_29 = {NIM_TRUE,
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_4)}
;
NIM_CONST tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q TM_zcCJBUqT9bHy43IBzmrbcrw_30 = {NIM_TRUE,
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_5)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_32, "len(a) == L seq modified while iterating over it", 48);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[2];
} TM_zcCJBUqT9bHy43IBzmrbcrw_36 = {{2, 2}, {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_5),
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_4)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_zcCJBUqT9bHy43IBzmrbcrw_35 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_zcCJBUqT9bHy43IBzmrbcrw_36);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_39, "tie", 3);
NIM_CONST tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q TM_zcCJBUqT9bHy43IBzmrbcrw_38 = {NIM_TRUE,
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_39)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_41, "going", 5);
NIM_CONST tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q TM_zcCJBUqT9bHy43IBzmrbcrw_40 = {NIM_FALSE,
((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_41)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_42, " | ", 3);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_45, "\012----------", 11);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_zcCJBUqT9bHy43IBzmrbcrw_44 = {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_45)}
;
NIM_CONST tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ TM_zcCJBUqT9bHy43IBzmrbcrw_49 = {((NI) 10),
((NI) 0)}
;
NIM_CONST tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ TM_zcCJBUqT9bHy43IBzmrbcrw_50 = {((NI) -10),
((NI) 0)}
;
NIM_CONST tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ TM_zcCJBUqT9bHy43IBzmrbcrw_51 = {((NI) 0),
((NI) 0)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_57, "Player ", 7);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_58, " enter your move: ", 18);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_60, "AI player turn!", 15);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_zcCJBUqT9bHy43IBzmrbcrw_59 = {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_60)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_62, "AI move!", 8);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_zcCJBUqT9bHy43IBzmrbcrw_61 = {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_62)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_64, "Random move!", 12);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_zcCJBUqT9bHy43IBzmrbcrw_63 = {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_64)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_66, "TIE!", 4);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_zcCJBUqT9bHy43IBzmrbcrw_65 = {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_66)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_67, "The winner is: ", 15);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_68, " !", 2);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_70, "    Tic Tac Toe 0.1.0 (MinMax version)\012    Arguments:\012      -h "
"| --help    : This screen\012      -a | --ai      : AI player [X or"
" O]\012      -l | --level   : Difficulty level 9 (High) to 0 (Low)\012"
"    ", 195);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_zcCJBUqT9bHy43IBzmrbcrw_69 = {((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_70)}
;
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_71, "", 0);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_72, "help", 4);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_73, "h", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_74, "aiplayer", 8);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_75, "a", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_76, "level", 5);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_77, "l", 1);
STRING_LITERAL(TM_zcCJBUqT9bHy43IBzmrbcrw_78, "AI Player: ", 11);
static N_NIMCALL(void, TM_zcCJBUqT9bHy43IBzmrbcrw_2)(void) {
	nimGCvisit((void*)nextPlayer_FD1svfwLer9czwZuWs3nhCA.data, 0);
}
static N_NIMCALL(void, TM_zcCJBUqT9bHy43IBzmrbcrw_6)(void) {
	nimGCvisit((void*)wins_VQ75bJhUsjDd9cVVt6yg5Eg, 0);
}
static N_NIMCALL(void, Marker_tyRef_4rGzeMi7MCB0z6Cv3SPX9bA)(void* p, NI op) {
	tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* a;
	a = (tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw*)p;
	nimGCvisit((void*)(*a).list, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw*, newBoard_1fU9a4wtv9aHhliHQffyd16A)(void) {
	tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* result;
	tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* b;
	tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* T1_;
	nimfr_("newBoard", "tic_tac_toe.nim");
{	result = (tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw*)0;
	nimln_(15, "tic_tac_toe.nim");
	T1_ = (tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw*)0;
	T1_ = (tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw*) newObj((&NTI_4rGzeMi7MCB0z6Cv3SPX9bA_), sizeof(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw));
	(*T1_).Sup.m_type = (&NTI_79afGQaHRQB5wDrFbwk3Skw_);
	b = T1_;
	nimln_(16, "tic_tac_toe.nim");
	genericSeqAssign((&(*b).list), TM_zcCJBUqT9bHy43IBzmrbcrw_17, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	nimln_(17, "tic_tac_toe.nim");
	result = b;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQtic_tac_toe)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_zcCJBUqT9bHy43IBzmrbcrw_33;
				NI TM_zcCJBUqT9bHy43IBzmrbcrw_34;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_zcCJBUqT9bHy43IBzmrbcrw_33 = addInt(result, ((NI) 1));
				result = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_33);
				nimln_(2188, "system.nim");
				TM_zcCJBUqT9bHy43IBzmrbcrw_34 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_34);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwtic_tac_toe)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQtic_tac_toe(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__SYCl19axYS7qpWNCbnZT1sg)(NimStringDesc* x) {
	NIM_BOOL result;
	nimfr_(":anonymous", "tic_tac_toe.nim");
	result = (NIM_BOOL)0;
	nimln_(28, "tic_tac_toe.nim");
	result = contains_jPdUhZfr9a8sH2V3ZBDljzwtic_tac_toe(TM_zcCJBUqT9bHy43IBzmrbcrw_35->data, TM_zcCJBUqT9bHy43IBzmrbcrw_35->Sup.len, x);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, done_mWiw9aAF1zaSpbM8WWAOoUQ)(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* this_0, tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q* Result) {
	nimfr_("done", "tic_tac_toe.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_ubXr9bFCXs9bc35NkwsYmx2Q_));
	{
		tySequence_qwqHTkRvwhrRyENtudHQ7g* w;
		NI i;
		NI L;
		NI T2_;
		w = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (wins_VQ75bJhUsjDd9cVVt6yg5Eg ? wins_VQ75bJhUsjDd9cVVt6yg5Eg->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_zcCJBUqT9bHy43IBzmrbcrw_31;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(wins_VQ75bJhUsjDd9cVVt6yg5Eg->Sup.len)) raiseIndexError();
				w = wins_VQ75bJhUsjDd9cVVt6yg5Eg->data[i];
				nimln_(22, "tic_tac_toe.nim");
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					if ((NU)(((NI) 0)) >= (NU)(w->Sup.len)) raiseIndexError();
					if ((NU)(w->data[((NI) 0)]) >= (NU)((*this_0).list->Sup.len)) raiseIndexError();
					if ((NU)(((NI) 1)) >= (NU)(w->Sup.len)) raiseIndexError();
					if ((NU)(w->data[((NI) 1)]) >= (NU)((*this_0).list->Sup.len)) raiseIndexError();
					T7_ = eqStrings((*this_0).list->data[w->data[((NI) 0)]], (*this_0).list->data[w->data[((NI) 1)]]);
					if (!(T7_)) goto LA8_;
					if ((NU)(((NI) 1)) >= (NU)(w->Sup.len)) raiseIndexError();
					if ((NU)(w->data[((NI) 1)]) >= (NU)((*this_0).list->Sup.len)) raiseIndexError();
					if ((NU)(((NI) 2)) >= (NU)(w->Sup.len)) raiseIndexError();
					if ((NU)(w->data[((NI) 2)]) >= (NU)((*this_0).list->Sup.len)) raiseIndexError();
					T7_ = eqStrings((*this_0).list->data[w->data[((NI) 1)]], (*this_0).list->data[w->data[((NI) 2)]]);
					LA8_: ;
					if (!T7_) goto LA9_;
					nimln_(23, "tic_tac_toe.nim");
					{
						if ((NU)(((NI) 0)) >= (NU)(w->Sup.len)) raiseIndexError();
						if ((NU)(w->data[((NI) 0)]) >= (NU)((*this_0).list->Sup.len)) raiseIndexError();
						if (!eqStrings((*this_0).list->data[w->data[((NI) 0)]], ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_4))) goto LA13_;
						nimln_(24, "tic_tac_toe.nim");
						(*Result).Field0 = TM_zcCJBUqT9bHy43IBzmrbcrw_29.Field0;
						unsureAsgnRef((void**) (&(*Result).Field1), copyString(TM_zcCJBUqT9bHy43IBzmrbcrw_29.Field1));
						goto BeforeRet_;
					}
					goto LA11_;
					LA13_: ;
					{
						nimln_(25, "tic_tac_toe.nim");
						if ((NU)(((NI) 0)) >= (NU)(w->Sup.len)) raiseIndexError();
						if ((NU)(w->data[((NI) 0)]) >= (NU)((*this_0).list->Sup.len)) raiseIndexError();
						if (!eqStrings((*this_0).list->data[w->data[((NI) 0)]], ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_5))) goto LA16_;
						nimln_(26, "tic_tac_toe.nim");
						(*Result).Field0 = TM_zcCJBUqT9bHy43IBzmrbcrw_30.Field0;
						unsureAsgnRef((void**) (&(*Result).Field1), copyString(TM_zcCJBUqT9bHy43IBzmrbcrw_30.Field1));
						goto BeforeRet_;
					}
					goto LA11_;
					LA16_: ;
					LA11_: ;
				}
				LA9_: ;
				nimln_(3809, "system.nim");
				TM_zcCJBUqT9bHy43IBzmrbcrw_31 = addInt(i, ((NI) 1));
				i = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_31);
				nimln_(3810, "system.nim");
				{
					NI T20_;
					T20_ = (wins_VQ75bJhUsjDd9cVVt6yg5Eg ? wins_VQ75bJhUsjDd9cVVt6yg5Eg->Sup.len : 0);
					if (!!((T20_ == L))) goto LA21_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_32));
				}
				LA21_: ;
			} LA4: ;
		}
	}
	nimln_(28, "tic_tac_toe.nim");
	{
		tyProc_45NwvjyfIWTGrNWgg5Pcig T25_;
		NIM_BOOL T26_;
		memset((void*)(&T25_), 0, sizeof(T25_));
		T25_.ClP_0 = ((TM_zcCJBUqT9bHy43IBzmrbcrw_37) (colonanonymous__SYCl19axYS7qpWNCbnZT1sg)); T25_.ClE_0 = NIM_NIL;
		T26_ = (NIM_BOOL)0;
		T26_ = all_d1z5CZM9aJLWjGEe6JKJ0eA((*this_0).list->data, (*this_0).list->Sup.len, T25_);
		if (!(T26_ == NIM_TRUE)) goto LA27_;
		nimln_(29, "tic_tac_toe.nim");
		(*Result).Field0 = TM_zcCJBUqT9bHy43IBzmrbcrw_38.Field0;
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(TM_zcCJBUqT9bHy43IBzmrbcrw_38.Field1));
		goto BeforeRet_;
	}
	goto LA23_;
	LA27_: ;
	{
		nimln_(31, "tic_tac_toe.nim");
		(*Result).Field0 = TM_zcCJBUqT9bHy43IBzmrbcrw_40.Field0;
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(TM_zcCJBUqT9bHy43IBzmrbcrw_40.Field1));
		goto BeforeRet_;
	}
	LA23_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_tySequence_phjbYJtsbOIAYa9be34hhZg)(void* p, NI op) {
	tySequence_phjbYJtsbOIAYa9be34hhZg* a;
	NI T1_;
	a = (tySequence_phjbYJtsbOIAYa9be34hhZg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__LChgG3UthCXxSHtCKOvdVw)(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* this_0) {
	NimStringDesc* result;
	tySequence_phjbYJtsbOIAYa9be34hhZg* rows;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T1_;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T2_;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T3_;
	nimfr_("$", "tic_tac_toe.nim");
	result = (NimStringDesc*)0;
	nimln_(34, "tic_tac_toe.nim");
	rows = (tySequence_phjbYJtsbOIAYa9be34hhZg*) newSeq((&NTI_phjbYJtsbOIAYa9be34hhZg_), 3);
	T1_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 0), ((NI) 2));
	asgnRefNoCycle((void**) (&rows->data[0]), X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg((*this_0).list->data, (*this_0).list->Sup.len, T1_));
	T2_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 3), ((NI) 5));
	asgnRefNoCycle((void**) (&rows->data[1]), X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg((*this_0).list->data, (*this_0).list->Sup.len, T2_));
	T3_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 6), ((NI) 8));
	asgnRefNoCycle((void**) (&rows->data[2]), X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg((*this_0).list->data, (*this_0).list->Sup.len, T3_));
	{
		NI x;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* row;
		NI i;
		x = (NI)0;
		row = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		nimln_(2285, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2286, "system.nim");
			while (1) {
				NI T7_;
				NI TM_zcCJBUqT9bHy43IBzmrbcrw_46;
				T7_ = (rows ? rows->Sup.len : 0);
				if (!(i < T7_)) goto LA6;
				nimln_(2287, "system.nim");
				x = i;
				if ((NU)(i) >= (NU)(rows->Sup.len)) raiseIndexError();
				row = rows->data[i];
				{
					NI y;
					NimStringDesc* cell;
					NI i_2;
					y = (NI)0;
					cell = (NimStringDesc*)0;
					nimln_(2285, "system.nim");
					i_2 = ((NI) 0);
					{
						nimln_(2286, "system.nim");
						while (1) {
							NI T11_;
							NI TM_zcCJBUqT9bHy43IBzmrbcrw_43;
							T11_ = (row ? row->Sup.len : 0);
							if (!(i_2 < T11_)) goto LA10;
							nimln_(2287, "system.nim");
							y = i_2;
							if ((NU)(i_2) >= (NU)(row->Sup.len)) raiseIndexError();
							cell = row->data[i_2];
							nimln_(37, "tic_tac_toe.nim");
							write_c4mGyJBvK73pdM22jiweKQ(stdout, cell);
							nimln_(38, "tic_tac_toe.nim");
							{
								if (!(y < ((NI) 2))) goto LA14_;
								write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_42));
							}
							LA14_: ;
							nimln_(2288, "system.nim");
							TM_zcCJBUqT9bHy43IBzmrbcrw_43 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_43);
						} LA10: ;
					}
				}
				nimln_(39, "tic_tac_toe.nim");
				{
					if (!(x < ((NI) 2))) goto LA18_;
					echoBinSafe(TM_zcCJBUqT9bHy43IBzmrbcrw_44, 1);
				}
				LA18_: ;
				nimln_(2288, "system.nim");
				TM_zcCJBUqT9bHy43IBzmrbcrw_46 = addInt(i, ((NI) 1));
				i = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_46);
			} LA6: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, emptySpots_Mg7cA0kmgz33yXQ15jA4dA)(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* this_0) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* emptyindices;
	nimfr_("emptySpots", "tic_tac_toe.nim");
{	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	nimln_(43, "tic_tac_toe.nim");
	emptyindices = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI) 0));
	{
		NimStringDesc* i;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
		NI i_2;
		NI L;
		NI T2_;
		i = (NimStringDesc*)0;
		colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		nimln_(44, "tic_tac_toe.nim");
		colontmp_ = (*this_0).list;
		nimln_(3805, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_zcCJBUqT9bHy43IBzmrbcrw_47;
				if (!(i_2 < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i_2) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				i = colontmp_->data[i_2];
				nimln_(45, "tic_tac_toe.nim");
				{
					NIM_BOOL T7_;
					NI T10_;
					NI T11_;
					T7_ = (NIM_BOOL)0;
					T7_ = nsuIsDigitStr(i);
					if (!T7_) goto LA8_;
					nimln_(46, "tic_tac_toe.nim");
					T10_ = (NI)0;
					T10_ = nsuParseInt(i);
					emptyindices = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) incrSeqV2(&(emptyindices)->Sup, sizeof(NI));
					T11_ = emptyindices->Sup.len++;
					emptyindices->data[T11_] = T10_;
				}
				LA8_: ;
				nimln_(3809, "system.nim");
				TM_zcCJBUqT9bHy43IBzmrbcrw_47 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_47);
				nimln_(3810, "system.nim");
				{
					NI T14_;
					T14_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T14_ == L))) goto LA15_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_32));
				}
				LA15_: ;
			} LA4: ;
		}
	}
	nimln_(47, "tic_tac_toe.nim");
	genericSeqAssign((&result), emptyindices, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt__4KfyMujq4uMvZmUtFDflyw)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ a, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ b) {
	NIM_BOOL result;
	nimfr_("<", "tic_tac_toe.nim");
{	result = (NIM_BOOL)0;
	nimln_(53, "tic_tac_toe.nim");
	result = (a.Field0 < b.Field0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_O12MqT52KmSXzoh9aR9a6H6A)(void* p, NI op) {
	tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* a;
	a = (tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A*)p;
	nimGCvisit((void*)(*a).currentPlayer, op);
	nimGCvisit((void*)(*a).board, op);
	nimGCvisit((void*)(*a).aiPlayer, op);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A*, newGame_Kd7XrxXB6GMIVqqmW09aeZQ)(NimStringDesc* aiPlayer, NI difficulty) {
	tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* result;
	tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* game;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("newGame", "tic_tac_toe.nim");
{	result = (tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A*)0;
	nimln_(64, "tic_tac_toe.nim");
	game = new_dGV9bEqtfd9aLwydHC659boag();
	nimln_(66, "tic_tac_toe.nim");
	asgnRef((void**) (&(*game).board), newBoard_1fU9a4wtv9aHhliHQffyd16A());
	nimln_(67, "tic_tac_toe.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*game).currentPlayer; (*game).currentPlayer = copyStringRC1(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_4));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(68, "tic_tac_toe.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = (*game).aiPlayer; (*game).aiPlayer = copyStringRC1(aiPlayer);
	if (T2_) nimGCunrefNoCycle(T2_);
	nimln_(69, "tic_tac_toe.nim");
	(*game).difficulty = difficulty;
	nimln_(71, "tic_tac_toe.nim");
	result = game;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, changePlayer_39csks0fo83GFyFbhmv2cMg)(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* this_0) {
	nimfr_("changePlayer", "tic_tac_toe.nim");
	nimln_(78, "tic_tac_toe.nim");
	asgnRefNoCycle((void**) (&(*this_0).currentPlayer), X5BX5D__bdg4B3o8C8pWA8Qu4aZLYg(nextPlayer_FD1svfwLer9czwZuWs3nhCA, (*this_0).currentPlayer));
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, map_U6WKGPJMPQQfVVS4uhKywgtic_tac_toe)(NimStringDesc** s, NI sLen_0, tyProc_lRW9cfxqfm1ql4gkxfLReYg op) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
	nimfr_("map", "sequtils.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(217, "sequtils.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), ((NI)chckRange(sLen_0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(218, "sequtils.nim");
		colontmp_ = sLen_0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_zcCJBUqT9bHy43IBzmrbcrw_54;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) >= (NU)(result->Sup.len)) raiseIndexError();
				nimln_(219, "sequtils.nim");
				if ((NU)(i) >= (NU)(sLen_0)) raiseIndexError();
				asgnRefNoCycle((void**) (&result->data[i]), op.ClE_0? op.ClP_0(s[i], op.ClE_0):((TM_zcCJBUqT9bHy43IBzmrbcrw_53)(op.ClP_0))(s[i]));
				nimln_(3522, "system.nim");
				TM_zcCJBUqT9bHy43IBzmrbcrw_54 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_54);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, colonanonymous__39bh9c6Htv4m4f54Tc9abE7Mg)(NimStringDesc* x) {
	NimStringDesc* result;
	nimfr_(":anonymous", "tic_tac_toe.nim");
	result = (NimStringDesc*)0;
	nimln_(99, "tic_tac_toe.nim");
	result = copyString(x);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, getBestMove_9bRYUKFkYtq9bByPc70XP9b9cw)(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* this_0, tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* board, NimStringDesc* player) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q T1_;
	NIM_BOOL done;
	NimStringDesc* winner;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* emptySpots;
	tySequence_8Np6tlClE5az1CyqZdN19bQ* moves;
	nimfr_("getBestMove", "tic_tac_toe.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(82, "tic_tac_toe.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	done_mWiw9aAF1zaSpbM8WWAOoUQ(board, (&T1_));
	done = (NIM_BOOL)0;
	done = T1_.Field0;
	winner = (NimStringDesc*)0;
	winner = T1_.Field1;
	nimln_(84, "tic_tac_toe.nim");
	{
		if (!done) goto LA4_;
		nimln_(85, "tic_tac_toe.nim");
		{
			if (!eqStrings(winner, (*this_0).aiPlayer)) goto LA8_;
			nimln_(86, "tic_tac_toe.nim");
			result = TM_zcCJBUqT9bHy43IBzmrbcrw_49;
			goto BeforeRet_;
		}
		goto LA6_;
		LA8_: ;
		{
			nimln_(398, "system.nim");
			nimln_(87, "tic_tac_toe.nim");
			if (!!(eqStrings(winner, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_39)))) goto LA11_;
			nimln_(88, "tic_tac_toe.nim");
			result = TM_zcCJBUqT9bHy43IBzmrbcrw_50;
			goto BeforeRet_;
		}
		goto LA6_;
		LA11_: ;
		{
			nimln_(90, "tic_tac_toe.nim");
			result = TM_zcCJBUqT9bHy43IBzmrbcrw_51;
			goto BeforeRet_;
		}
		LA6_: ;
	}
	LA4_: ;
	nimln_(92, "tic_tac_toe.nim");
	emptySpots = emptySpots_Mg7cA0kmgz33yXQ15jA4dA(board);
	nimln_(93, "tic_tac_toe.nim");
	moves = newSeq_r6F9aBPw1h0wreCPkFTV9ckQ(((NI) 0));
	{
		NI pos;
		NI i;
		NI L;
		NI T15_;
		pos = (NI)0;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T15_ = (emptySpots ? emptySpots->Sup.len : 0);
		L = T15_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw* newBoard;
				tyProc_lRW9cfxqfm1ql4gkxfLReYg T18_;
				NimStringDesc* T19_;
				NI score;
				NimStringDesc* T20_;
				tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T21_;
				NI pos_2;
				tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ move;
				NI T22_;
				NI TM_zcCJBUqT9bHy43IBzmrbcrw_56;
				if (!(i < L)) goto LA17;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(emptySpots->Sup.len)) raiseIndexError();
				pos = emptySpots->data[i];
				nimln_(97, "tic_tac_toe.nim");
				newBoard = newBoard_1fU9a4wtv9aHhliHQffyd16A();
				nimln_(99, "tic_tac_toe.nim");
				memset((void*)(&T18_), 0, sizeof(T18_));
				T18_.ClP_0 = ((TM_zcCJBUqT9bHy43IBzmrbcrw_55) (colonanonymous__39bh9c6Htv4m4f54Tc9abE7Mg)); T18_.ClE_0 = NIM_NIL;
				asgnRefNoCycle((void**) (&(*newBoard).list), map_U6WKGPJMPQQfVVS4uhKywgtic_tac_toe((*board).list->data, (*board).list->Sup.len, T18_));
				if ((NU)(pos) >= (NU)((*newBoard).list->Sup.len)) raiseIndexError();
				nimln_(101, "tic_tac_toe.nim");
				T19_ = (NimStringDesc*)0;
				T19_ = (*newBoard).list->data[pos]; (*newBoard).list->data[pos] = copyStringRC1(player);
				if (T19_) nimGCunrefNoCycle(T19_);
				nimln_(103, "tic_tac_toe.nim");
				T20_ = (NimStringDesc*)0;
				T20_ = X5BX5D__bdg4B3o8C8pWA8Qu4aZLYg(nextPlayer_FD1svfwLer9czwZuWs3nhCA, player);
				T21_ = getBestMove_9bRYUKFkYtq9bByPc70XP9b9cw(this_0, newBoard, T20_);
				score = T21_.Field0;
				nimln_(104, "tic_tac_toe.nim");
				pos_2 = pos;
				nimln_(105, "tic_tac_toe.nim");
				move.Field0 = score;
				move.Field1 = pos_2;
				nimln_(106, "tic_tac_toe.nim");
				moves = (tySequence_8Np6tlClE5az1CyqZdN19bQ*) incrSeqV2(&(moves)->Sup, sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ));
				T22_ = moves->Sup.len++;
				moves->data[T22_] = move;
				nimln_(3809, "system.nim");
				TM_zcCJBUqT9bHy43IBzmrbcrw_56 = addInt(i, ((NI) 1));
				i = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_56);
				nimln_(3810, "system.nim");
				{
					NI T25_;
					T25_ = (emptySpots ? emptySpots->Sup.len : 0);
					if (!!((T25_ == L))) goto LA26_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_32));
				}
				LA26_: ;
			} LA17: ;
		}
	}
	nimln_(108, "tic_tac_toe.nim");
	{
		if (!eqStrings(player, (*this_0).aiPlayer)) goto LA30_;
		nimln_(109, "tic_tac_toe.nim");
		result = max_NN3SMNaATnaYmB26AVHTyQ(moves->data, moves->Sup.len);
		goto BeforeRet_;
	}
	goto LA28_;
	LA30_: ;
	{
		nimln_(111, "tic_tac_toe.nim");
		result = min_NN3SMNaATnaYmB26AVHTyQ_2(moves->data, moves->Sup.len);
		goto BeforeRet_;
	}
	LA28_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, startGame_39csks0fo83GFyFbhmv2cMg_2)(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* this_0) {
	nimfr_("startGame", "tic_tac_toe.nim");
	{
		nimln_(114, "tic_tac_toe.nim");
		while (1) {
			tyArray_nHXaesL0DJZHyVS07ARPRA T3_;
			tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q T25_;
			NIM_BOOL done;
			NimStringDesc* winner;
			nimln_(115, "tic_tac_toe.nim");
			memset((void*)T3_, 0, sizeof(T3_));
			T3_[0] = dollar__LChgG3UthCXxSHtCKOvdVw((*this_0).board);
			echoBinSafe(T3_, 1);
			nimln_(116, "tic_tac_toe.nim");
			{
				NimStringDesc* T8_;
				NimStringDesc* move;
				NI T9_;
				NimStringDesc* T10_;
				nimln_(398, "system.nim");
				nimln_(116, "tic_tac_toe.nim");
				if (!!(eqStrings((*this_0).aiPlayer, (*this_0).currentPlayer))) goto LA6_;
				nimln_(117, "tic_tac_toe.nim");
				T8_ = (NimStringDesc*)0;
				T8_ = rawNewString((*this_0).currentPlayer->Sup.len + 25);
appendString(T8_, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_57));
appendString(T8_, (*this_0).currentPlayer);
appendString(T8_, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_58));
				write_c4mGyJBvK73pdM22jiweKQ(stdout, T8_);
				nimln_(118, "tic_tac_toe.nim");
				move = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
				nimln_(119, "tic_tac_toe.nim");
				T9_ = (NI)0;
				T9_ = nsuParseInt(move);
				if ((NU)(T9_) >= (NU)((*(*this_0).board).list->Sup.len)) raiseIndexError();
				T10_ = (NimStringDesc*)0;
				T10_ = (*(*this_0).board).list->data[T9_]; (*(*this_0).board).list->data[T9_] = copyStringRC1((*this_0).currentPlayer);
				if (T10_) nimGCunrefNoCycle(T10_);
			}
			goto LA4_;
			LA6_: ;
			{
				nimln_(121, "tic_tac_toe.nim");
				{
					tySequence_qwqHTkRvwhrRyENtudHQ7g* currentEmptySpots;
					if (!eqStrings((*this_0).currentPlayer, (*this_0).aiPlayer)) goto LA14_;
					nimln_(122, "tic_tac_toe.nim");
					echoBinSafe(TM_zcCJBUqT9bHy43IBzmrbcrw_59, 1);
					nimln_(123, "tic_tac_toe.nim");
					currentEmptySpots = emptySpots_Mg7cA0kmgz33yXQ15jA4dA((*this_0).board);
					nimln_(125, "tic_tac_toe.nim");
					{
						NI T18_;
						tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ move_2;
						NimStringDesc* T21_;
						T18_ = (currentEmptySpots ? currentEmptySpots->Sup.len : 0);
						if (!(T18_ <= (*this_0).difficulty)) goto LA19_;
						nimln_(126, "tic_tac_toe.nim");
						echoBinSafe(TM_zcCJBUqT9bHy43IBzmrbcrw_61, 1);
						nimln_(127, "tic_tac_toe.nim");
						move_2 = getBestMove_9bRYUKFkYtq9bByPc70XP9b9cw(this_0, (*this_0).board, (*this_0).aiPlayer);
						if ((NU)(move_2.Field1) >= (NU)((*(*this_0).board).list->Sup.len)) raiseIndexError();
						nimln_(128, "tic_tac_toe.nim");
						T21_ = (NimStringDesc*)0;
						T21_ = (*(*this_0).board).list->data[move_2.Field1]; (*(*this_0).board).list->data[move_2.Field1] = copyStringRC1((*this_0).aiPlayer);
						if (T21_) nimGCunrefNoCycle(T21_);
					}
					goto LA16_;
					LA19_: ;
					{
						NI T23_;
						NimStringDesc* T24_;
						nimln_(131, "tic_tac_toe.nim");
						echoBinSafe(TM_zcCJBUqT9bHy43IBzmrbcrw_63, 1);
						nimln_(132, "tic_tac_toe.nim");
						T23_ = (NI)0;
						T23_ = rand_ZFto5dQROl6EDzKy42ijyA(currentEmptySpots->data, currentEmptySpots->Sup.len);
						if ((NU)(T23_) >= (NU)((*(*this_0).board).list->Sup.len)) raiseIndexError();
						T24_ = (NimStringDesc*)0;
						T24_ = (*(*this_0).board).list->data[T23_]; (*(*this_0).board).list->data[T23_] = copyStringRC1((*this_0).aiPlayer);
						if (T24_) nimGCunrefNoCycle(T24_);
					}
					LA16_: ;
				}
				LA14_: ;
			}
			LA4_: ;
			nimln_(135, "tic_tac_toe.nim");
			changePlayer_39csks0fo83GFyFbhmv2cMg(this_0);
			nimln_(136, "tic_tac_toe.nim");
			memset((void*)(&T25_), 0, sizeof(T25_));
			done_mWiw9aAF1zaSpbM8WWAOoUQ((*this_0).board, (&T25_));
			done = (NIM_BOOL)0;
			done = T25_.Field0;
			winner = (NimStringDesc*)0;
			winner = T25_.Field1;
			nimln_(138, "tic_tac_toe.nim");
			{
				tyArray_nHXaesL0DJZHyVS07ARPRA T30_;
				if (!done) goto LA28_;
				nimln_(139, "tic_tac_toe.nim");
				memset((void*)T30_, 0, sizeof(T30_));
				T30_[0] = dollar__LChgG3UthCXxSHtCKOvdVw((*this_0).board);
				echoBinSafe(T30_, 1);
				nimln_(140, "tic_tac_toe.nim");
				{
					if (!eqStrings(winner, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_39))) goto LA33_;
					nimln_(141, "tic_tac_toe.nim");
					echoBinSafe(TM_zcCJBUqT9bHy43IBzmrbcrw_65, 1);
				}
				goto LA31_;
				LA33_: ;
				{
					tyArray_24KAM9afIUgUaqBaEBB6r9bg T36_;
					nimln_(143, "tic_tac_toe.nim");
					memset((void*)T36_, 0, sizeof(T36_));
					T36_[0] = copyString(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_67));
					T36_[1] = copyString(winner);
					T36_[2] = copyString(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_68));
					echoBinSafe(T36_, 3);
				}
				LA31_: ;
				nimln_(144, "tic_tac_toe.nim");
				goto LA1;
			}
			LA28_: ;
		}
	} LA1: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, writeHelp_AL8TA3zYBSG83tMKprIPlw)(void) {
	nimfr_("writeHelp", "tic_tac_toe.nim");
	nimln_(147, "tic_tac_toe.nim");
	echoBinSafe(TM_zcCJBUqT9bHy43IBzmrbcrw_69, 1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, cli_74KmN19crw4yATb9b6mHZ0Gw)(void) {
	NimStringDesc* aiplayer;
	NI difficulty;
	tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A* g;
	nimfr_("cli", "tic_tac_toe.nim");
{	nimln_(157, "tic_tac_toe.nim");
	aiplayer = copyString(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_71));
	nimln_(158, "tic_tac_toe.nim");
	difficulty = ((NI) 9);
	{
		tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA kind;
		NimStringDesc* key;
		NimStringDesc* val;
		tyObject_OptParser_fe5bDDfRbVwQIuUOouExnA p;
		kind = (tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA)0;
		key = (NimStringDesc*)0;
		val = (NimStringDesc*)0;
		memset((void*)(&p), 0, sizeof(p));
		p.Sup.m_type = (&NTI_fe5bDDfRbVwQIuUOouExnA_);
		nimln_(205, "parseopt.nim");
		initOptParser_xt25Cv9cQqaNt3Mscl7nHFA(((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_71), (&p));
		{
			nimln_(206, "parseopt.nim");
			while (1) {
				nimln_(207, "parseopt.nim");
				nponext((&p));
				nimln_(208, "parseopt.nim");
				{
					if (!(p.kind == ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 0))) goto LA6_;
					goto LA2;
				}
				LA6_: ;
				nimln_(209, "parseopt.nim");
				kind = p.kind;
				key = p.key;
				val = p.val;
				nimln_(161, "tic_tac_toe.nim");
				switch (kind) {
				case ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 1):
				case ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 2):
				case ((tyEnum_CmdLineKind_XkdXq9atxjiuhkFFh0XYrSA) 3):
				{
					nimln_(163, "tic_tac_toe.nim");
					if (eqStrings(key, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_72))) goto LA9_;
					if (eqStrings(key, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_73))) goto LA9_;
					if (eqStrings(key, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_74))) goto LA10_;
					if (eqStrings(key, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_75))) goto LA10_;
					if (eqStrings(key, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_76))) goto LA11_;
					if (eqStrings(key, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_77))) goto LA11_;
					goto LA12_;
					LA9_: ;
					{
						nimln_(165, "tic_tac_toe.nim");
						writeHelp_AL8TA3zYBSG83tMKprIPlw();
						nimln_(166, "tic_tac_toe.nim");
						goto BeforeRet_;
					}
					goto LA13_;
					LA10_: ;
					{
						tyArray_nHXaesL0DJZHyVS07ARPRA T16_;
						NimStringDesc* T17_;
						nimln_(168, "tic_tac_toe.nim");
						memset((void*)T16_, 0, sizeof(T16_));
						T17_ = (NimStringDesc*)0;
						T17_ = rawNewString(val->Sup.len + 11);
appendString(T17_, ((NimStringDesc*) &TM_zcCJBUqT9bHy43IBzmrbcrw_78));
appendString(T17_, val);
						T16_[0] = T17_;
						echoBinSafe(T16_, 1);
						nimln_(169, "tic_tac_toe.nim");
						aiplayer = copyString(val);
					}
					goto LA13_;
					LA11_: ;
					{
						nimln_(171, "tic_tac_toe.nim");
						difficulty = nsuParseInt(val);
					}
					goto LA13_;
					LA12_: ;
					{
					}
					LA13_: ;
				}
				break;
				default:
				{
				}
				break;
				}
			}
		} LA2: ;
	}
	nimln_(177, "tic_tac_toe.nim");
	g = newGame_Kd7XrxXB6GMIVqqmW09aeZQ(aiplayer, difficulty);
	nimln_(178, "tic_tac_toe.nim");
	startGame_39csks0fo83GFyFbhmv2cMg_2(g);
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_zcCJBUqT9bHy43IBzmrbcrw_79;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_zcCJBUqT9bHy43IBzmrbcrw_79 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_79) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_9b2gsSftUX2T20Nv0GQyaugtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_zcCJBUqT9bHy43IBzmrbcrw_80;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_zcCJBUqT9bHy43IBzmrbcrw_80 = subInt(((NI) -1), h);
	result = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_80);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_t4rnRU9ceXEIukTl9b0Ap10Qtables)(tyObject_Table_MCOwvEd9cS88yVcSkkw9bO9aQ t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_zcCJBUqT9bHy43IBzmrbcrw_81;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_zcCJBUqT9bHy43IBzmrbcrw_81 = subInt(((NI) -1), h);
	result = (NI)(TM_zcCJBUqT9bHy43IBzmrbcrw_81);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_strformatDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_randomDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_parseoptDatInit000();
	tic_tac_toeDatInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_unicodeInit000();
	stdlib_strformatInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_randomInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_parseoptInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("tic_tac_toe", "tic_tac_toe.nim");
nimRegisterGlobalMarker(TM_zcCJBUqT9bHy43IBzmrbcrw_2);
nimRegisterGlobalMarker(TM_zcCJBUqT9bHy43IBzmrbcrw_6);
	nimln_(3, "tic_tac_toe.nim");
	randomize_RtUZt2O8eA6Y5pFWOsdgjg();
	nimln_(5, "tic_tac_toe.nim");
	toTable_aS0SHfzTdtCR7Owy1P12DA(TM_zcCJBUqT9bHy43IBzmrbcrw_3, 2, (&nextPlayer_FD1svfwLer9czwZuWs3nhCA));
	nimln_(12, "tic_tac_toe.nim");
	genericSeqAssign((&wins_VQ75bJhUsjDd9cVVt6yg5Eg), TM_zcCJBUqT9bHy43IBzmrbcrw_7, (&NTI_PSP8snSsRoFs9cDiya9bd7UQ_));
	nimln_(181, "tic_tac_toe.nim");
	cli_74KmN19crw4yATb9b6mHZ0Gw();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, tic_tac_toeDatInit000)(void) {
static TNimNode* TM_zcCJBUqT9bHy43IBzmrbcrw_28[2];
static TNimNode* TM_zcCJBUqT9bHy43IBzmrbcrw_48[4];
static TNimNode* TM_zcCJBUqT9bHy43IBzmrbcrw_52[2];
static TNimNode TM_zcCJBUqT9bHy43IBzmrbcrw_0[12];
NTI_79afGQaHRQB5wDrFbwk3Skw_.size = sizeof(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw);
NTI_79afGQaHRQB5wDrFbwk3Skw_.kind = 17;
NTI_79afGQaHRQB5wDrFbwk3Skw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[0].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[0].offset = offsetof(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw, list);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[0].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[0].name = "list";
NTI_79afGQaHRQB5wDrFbwk3Skw_.node = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[0];
NTI_4rGzeMi7MCB0z6Cv3SPX9bA_.size = sizeof(tyObject_BoardcolonObjectType__79afGQaHRQB5wDrFbwk3Skw*);
NTI_4rGzeMi7MCB0z6Cv3SPX9bA_.kind = 22;
NTI_4rGzeMi7MCB0z6Cv3SPX9bA_.base = (&NTI_79afGQaHRQB5wDrFbwk3Skw_);
NTI_4rGzeMi7MCB0z6Cv3SPX9bA_.marker = Marker_tyRef_4rGzeMi7MCB0z6Cv3SPX9bA;
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.size = sizeof(tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q);
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.kind = 18;
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.base = 0;
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.flags = 2;
TM_zcCJBUqT9bHy43IBzmrbcrw_28[0] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[2];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[2].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[2].offset = offsetof(tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q, Field0);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[2].name = "Field0";
TM_zcCJBUqT9bHy43IBzmrbcrw_28[1] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[3];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[3].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[3].offset = offsetof(tyTuple_ubXr9bFCXs9bc35NkwsYmx2Q, Field1);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[3].name = "Field1";
TM_zcCJBUqT9bHy43IBzmrbcrw_0[1].len = 2; TM_zcCJBUqT9bHy43IBzmrbcrw_0[1].kind = 2; TM_zcCJBUqT9bHy43IBzmrbcrw_0[1].sons = &TM_zcCJBUqT9bHy43IBzmrbcrw_28[0];
NTI_ubXr9bFCXs9bc35NkwsYmx2Q_.node = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[1];
NTI_phjbYJtsbOIAYa9be34hhZg_.size = sizeof(tySequence_phjbYJtsbOIAYa9be34hhZg*);
NTI_phjbYJtsbOIAYa9be34hhZg_.kind = 24;
NTI_phjbYJtsbOIAYa9be34hhZg_.base = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
NTI_phjbYJtsbOIAYa9be34hhZg_.flags = 2;
NTI_phjbYJtsbOIAYa9be34hhZg_.marker = Marker_tySequence_phjbYJtsbOIAYa9be34hhZg;
NTI_RWfNK71Zxw13vryRqXAD1A_.size = sizeof(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A);
NTI_RWfNK71Zxw13vryRqXAD1A_.kind = 17;
NTI_RWfNK71Zxw13vryRqXAD1A_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_zcCJBUqT9bHy43IBzmrbcrw_48[0] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[5];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[5].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[5].offset = offsetof(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A, currentPlayer);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[5].name = "currentPlayer";
TM_zcCJBUqT9bHy43IBzmrbcrw_48[1] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[6];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[6].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[6].offset = offsetof(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A, board);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[6].typ = (&NTI_4rGzeMi7MCB0z6Cv3SPX9bA_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[6].name = "board";
TM_zcCJBUqT9bHy43IBzmrbcrw_48[2] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[7];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[7].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[7].offset = offsetof(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A, aiPlayer);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[7].name = "aiPlayer";
TM_zcCJBUqT9bHy43IBzmrbcrw_48[3] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[8];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[8].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[8].offset = offsetof(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A, difficulty);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[8].name = "difficulty";
TM_zcCJBUqT9bHy43IBzmrbcrw_0[4].len = 4; TM_zcCJBUqT9bHy43IBzmrbcrw_0[4].kind = 2; TM_zcCJBUqT9bHy43IBzmrbcrw_0[4].sons = &TM_zcCJBUqT9bHy43IBzmrbcrw_48[0];
NTI_RWfNK71Zxw13vryRqXAD1A_.node = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[4];
NTI_O12MqT52KmSXzoh9aR9a6H6A_.size = sizeof(tyObject_GamecolonObjectType__RWfNK71Zxw13vryRqXAD1A*);
NTI_O12MqT52KmSXzoh9aR9a6H6A_.kind = 22;
NTI_O12MqT52KmSXzoh9aR9a6H6A_.base = (&NTI_RWfNK71Zxw13vryRqXAD1A_);
NTI_O12MqT52KmSXzoh9aR9a6H6A_.marker = Marker_tyRef_O12MqT52KmSXzoh9aR9a6H6A;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.size = sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ);
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.kind = 18;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.base = 0;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.flags = 3;
TM_zcCJBUqT9bHy43IBzmrbcrw_52[0] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[10];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[10].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[10].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field0);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[10].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[10].name = "Field0";
TM_zcCJBUqT9bHy43IBzmrbcrw_52[1] = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[11];
TM_zcCJBUqT9bHy43IBzmrbcrw_0[11].kind = 1;
TM_zcCJBUqT9bHy43IBzmrbcrw_0[11].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field1);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[11].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_zcCJBUqT9bHy43IBzmrbcrw_0[11].name = "Field1";
TM_zcCJBUqT9bHy43IBzmrbcrw_0[9].len = 2; TM_zcCJBUqT9bHy43IBzmrbcrw_0[9].kind = 2; TM_zcCJBUqT9bHy43IBzmrbcrw_0[9].sons = &TM_zcCJBUqT9bHy43IBzmrbcrw_52[0];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.node = &TM_zcCJBUqT9bHy43IBzmrbcrw_0[9];
}

